# Google App Engine configuration
runtime: python311

env_variables:
  SECRET_KEY: 'your-secret-key-here'
  DATABASE_URL: 'your-database-url-here'
  SPOTIFY_CLIENT_ID: 'your-spotify-client-id'
  SPOTIFY_CLIENT_SECRET: 'your-spotify-client-secret'
  SPOTIFY_REDIRECT_URI: 'https://your-app.appspot.com/spotify/callback'
  REDIS_HOST: 'your-redis-host'
  REDIS_PORT: '6379'

automatic_scaling:
  min_instances: 1
  max_instances: 10
